#!/bin/bash

inputSizes=(18 20)
inputTypes=("sorted" "random")
num_procs=(16 32)

for size in "${inputSizes[@]}"; do
    for type in "${inputTypes[@]}"; do
        for proc in "${num_procs[@]}"; do
            for thread in "${num_threads[@]}"; do
                # Call your program with the specified parameters
                sbatch mpi.grace_job $((2**size)) $proc "$type" 
            done
        done
    done
done